book_talking:
    resource: "@BookTalkingBundle/Resources/config/routing.yml"
    prefix:   /

acme_blog:
    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
    prefix:   /

book_request:
    resource: "@BookRequestBundle/Resources/config/routing.yml"
    prefix:   /



